name: tamashelf
description: TamaShelf - Lecteur manga hors-ligne
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  http: ^1.1.0
  archive: ^3.4.9
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path: ^1.8.3
  wakelock_plus: ^1.2.8
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: AnimeAce2
      fonts:
        - asset: assets/fonts/animeace2_reg.ttf
        - asset: assets/fonts/animeace2_bld.ttf
          weight: 700
        - asset: assets/fonts/animeace2_ital.ttf
          style: italic
    - family: CCWildWords
      fonts:
        - asset: assets/fonts/CC Wild Words Roman.ttf
        - asset: assets/fonts/CC Wild Words Italic.ttf
          style: italic
        - asset: assets/fonts/CC Wild Words Bold Italic.ttf
          weight: 700
          style: italic
